POST http://localhost:8080/validation
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=10

###

POST http://localhost:8080/non-validation
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=ddd

###

POST http://localhost:8080/validation/2
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=ddd


###

POST http://localhost:8080/users
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=ten

###

POST http://localhost:8080/admin
Content-Type: application/x-www-form-urlencoded

password=55555